version: "3.9"

services:
    app:
        container_name: nginx-sample
        image: nginx-sample
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"